### ISSUE TITLE
Two typos in NixOS install guide

### ISSUE THREAD

**Issue by aquarial** [adelbertc/adelbertc.github.io#1]
I was able to follow this guide to install NixOS on my laptop, awesome job! I ran into two issues while following along:

1) Step 6 of the LUKS list should be `lvcreate -L <# of GB of swap space you want>G -n swap vg`. The command right now is missing the `-n` flag before swap.

2) The example configuration.nix addition is missing quotes around the device parameter

**Comment by adelbertc** [comment]
@aquarial Oof, sorry, just saw this! Thank you for the issue, should be fixed now, and glad the guide was useful to you!
